# Generated by Django 4.2.5 on 2025-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='dalle_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
